version: '3'
services:
  app:
    build: .
    container_name: ruby_app
    volumes:
      - .:/app
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    stdin_open: true
    tty: true
